name = "QHull"
uuid = "a8468747-bd6f-53ef-9e5c-744dbc5c59e7"
repo = "https://github.com/JuliaPolyhedra/QHull.jl.git"
version = "0.2.4"

[deps]
Polyhedra = "67491407-f73d-577b-9b50-8179a7c68029"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Polyhedra = "0.6.8, 0.7"
PyCall = "1.91"
StaticArrays = "0.12, 1.0"
julia = "1"

[extras]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Combinatorics", "GLPK", "GeometryBasics", "JuMP", "LinearAlgebra", "RecipesBase", "SparseArrays", "Test"]
